/// This file is generated by `tool/generate_config.dart`.
/// Do not modify this file directly.

const List<String> monsterLabels = ["inox_bodyguard","sun_demon","ancient_artillery","stone_golem","inox_archer","inox_shaman","inox_guard","harrower_infester","lurker","flame_demon","city_archer","rending_drake","cave_bear","savvas_lavaflow","vermling_scout","forest_imp","deep_terror","ooze","bandit_guard","living_bones","savvas_icestorm","living_spirit","city_guard","bandit_archer","wind_demon","earth_demon","cultist","vermling_shaman","black_imp","giant_viper","hound","living_corpse","night_demon","spitting_drake","frost_demon","jekserah","bandit_commander","captain_of_the_guard","merciless_overseer","the_betrayer","the_colorless","the_gloom","the_sightless_eye","dark_rider","winged_horror","prime_demon","elder_drake"];

